version: '3'
services:
  nginx-proxy:
    image: nginx:1.18.0
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  karrot:
    image: xiu0327/karrot:v1
    ports:
      - "8080:8080"
    depends_on:
      - nginx-proxy